.TH jack_meter "1" 0.3 "September 2005"
.SH NAME
jack_meter \- Console based Digital Peak Meter for JACK
.SH SYNOPSYS
\fBjack_meter\fR [ \-f \fIfreqency\fR ] [ \-r \fIref-level\fR ]
[ \-w \fIwidth\fR ] [\-n ] [ \fI<port>\fR, ... ]
.br
\fBjack_meter\fR
\-h

.SH DESCRIPTION
\fBjack_meter\fR is a basic console based DPM (Digital Peak Meter).
I wrote it for quickly checking remote signal levels, without having to 
run X11 to use a pretty graphical meter such as \fBmeterbridge\fR.

The port parameter is optional - when missing then you have to connect 
up the meter to an input port manually. 
If more than one port is specified then the inputs are mixed.

.SH OPTIONS
.TP
\fB\-f \fI freqency \fR
.br
How many times per second to refresh the meter. Default is \fB8\fR.
.TP
\fB\-r \fI ref-level \fR
.br
The reference signal level for 0dB on the meter.
.TP
\fB\-w \fI width \fR
.br
The width of the meter (number of characters). The default is \fB79\fR,
one less than the typical terminal width.
\fB\-n
.br
Outputs meter level as a number in decibels instead of a bar graph display. 

.SH SEE ALSO:
.br
http://www.ecs.soton.ac.uk/~njh/jackmeter/
.br
http://plugin.org.uk/meterbridge/
.br
http://jackit.sourceforge.net/

.SH AUTHORS
Nicholas Humfrey <njh@aelius.com>
